version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-maka082"
resolve_s3 = true
s3_prefix = "sam-app-maka082"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"pgr301-couch-explorers\" KandidatNr=\"28\""
image_repositories = []
