name: Multi-Job Workflow

on:
  push:
    branches:
      - main
      - "*"

jobs:
  terraform-init:
    name: Initialize Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Initialize Terraform
        run: |
          cd infra
          terraform init

  terraform-plan:
    name: Terraform Plan
    needs: terraform-init  
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main'  #Runs when pushed to other branch but main

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Plan Terraform
        run: |
          cd infra
          terraform plan

  terraform-apply:
    name: Terraform Apply
    needs: terraform-init  
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'  #Run only if pushed to main

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Apply Terraform
        run: |
          cd infra
          terraform apply -auto-approve
