name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      working-directory: java_sqs_client
      run: docker build -t maka082/java-sqs-client .

    - name: Tag Docker Image
      run: docker tag maka082/java-sqs-client:latest maka082/java-sqs-client:latest

  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: docker push maka082/java-sqs-client:latest
