name: Build and push Docker image 

on:
  push:
    branches:
      - main

jobs:
  Build-and-push:
    runs-on: ubuntu-latest
    #Check code
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    #Login using username and passwored stored in my github repo secrets
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #Build
    - name: Docker Build
      working-directory: java_sqs_client
      run: docker build -t maka082/java-sqs-client .
    #Push
    - name: Docker Push
      run: docker push maka082/java-sqs-client:latest
